package io.avalia.samba;

import org.junit.Assert;
import org.junit.Test;

/**
 * *** IMPORTANT WARNING : DO NOT EDIT THIS FILE ***
 * 
 * This file is used to specify what you have to implement. To check your work,
 * we will run our own copy of the automated tests. If you change this file,
 * then you will introduce a change of specification!!!
 * 
 * @author Olivier Liechti
 */
public class ChocalhoTest {

	@Test
	public void thereShouldBeAnIInstrumentInterfaceAndAChocalhoClass() {
		IInstrument Chocalho = new Chocalho();
		Assert.assertNotNull(Chocalho);
	}

	@Test
	public void itShouldBePossibleToPlayAnInstrument() {
		IInstrument Chocalho = new Chocalho();
		String sound = Chocalho.play();
		Assert.assertNotNull(sound);
	}

	@Test
	public void aChocalhoShouldMakeChicChic() {
		IInstrument Chocalho = new Chocalho();
		String sound = Chocalho.play();
		Assert.assertEquals("chic-chic", sound);
	}

	@Test
	public void aChocalhoShouldBeLouderThanAFlute() {
		IInstrument Chocalho = new Chocalho();
		IInstrument flute = new Flute();
		int ChocalhoVolume = Chocalho.getSoundVolume();
		int fluteVolume = flute.getSoundVolume();
		Assert.assertTrue(ChocalhoVolume > fluteVolume);
	}

	@Test
	public void aChocalhoShouldBeGolden() {
		IInstrument Chocalho = new Chocalho();
		String color = Chocalho.getColor();
		Assert.assertEquals("rosa", color);
	}

}
